const ERROR_CODE = {
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  GOOGLE_UNAUTHORIZED: 'GOOGLE_UNAUTHORIZED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DEVICE_NOT_VERIFIED: 'DEVICE_NOT_VERIFIED',
  OAUTH_CODE_INVALID: 'OAUTH_CODE_INVALID',
  OAUTH_CODE_EXPIRED: 'OAUTH_CODE_EXPIRED',
} as const;

export default ERROR_CODE;
