const ERROR_CODE = {
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  GOOGLE_UNAUTHORIZED: 'GOOGLE_UNAUTHORIZED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DEVICE_NOT_VERIFIED: 'DEVICE_NOT_VERIFIED',
} as const;

export default ERROR_CODE;
